name: Build

on: [push]
  #   push:
  #     branches: [ master ]
  #   pull_request:
  #     branches: [ master ]
  # 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2



    - name: Run .travis.yml build script
      uses: ktomk/run-travis-yml@v1
      with:
        file: .travis.yml
        steps: |
          before_install
          script
        allow-failure: false
    - name: Display structure of downloaded files
      run: ls 

    - uses: actions/upload-artifact@v2
      with:
        name: output
        path: esp-link-no.tag.tgz
